# Generated by Django 4.2.4 on 2023-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='initial_deposite_date',
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='initial_deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
