# Generated by Django 4.2.4 on 2023-09-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userbankaccount_initial_deposite_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankruptcy_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
